countries={
'Afghanistan': 'AF', 
'Aland islands': 'AX', 
'Albania': 'AL', 
'Algeria': 'DZ', 
'American samioa': 'AS', 
'Andorra': 'AD', 
'Angola': 'AO', 
'Anguilla': 'AI', 
'Antarctica': 'AQ', 
'Antigua and barbuda': 'AG', 
'Argentina': 'AR', 
'Armenia': 'AM', 
'Aruba': 'AW', 
'Australia': 'AU', 
'Austria': 'AT', 
'Azerbaijan': 'AZ', 
'Bahamas': 'BS', 
'Bahrain': 'BH', 
'Bangladesh': 'BD', 
'Barbados': 'BB', 
'Belarus': 'BY', 
'Belgium': 'BE', 
'Belize': 'BZ', 
'Benin': 'BJ', 
'Bermuda': 'BM', 
'Bhutan': 'BT', 
'Bolivia': 'BO', 
'Bonaire': 'BQ', 
'Bosnia and herzegovina': 'BA', 
'Botswana': 'BW', 
'Bouvet island': 'BV', 
'Brazil': 'BR', 
'British indian ocean territory': 'IO', 
'Brunei': 'BN', 
'Bulgaria': 'BG', 
'Burkina Faso': 'BF', 
'Burundi': 'BI', 
'Cambodia': 'KH', 
'Cameroon': 'CM', 
'Canada': 'CA', 
'Cape Verde': 'CV', 
'Cayman Islands': 'KY', 
'Central African Republic': 'CF', 
'Chad': 'TD', 
'Chile': 'CL', 
'China': 'CN', 
'Christmas Island': 'CX', 
'Cocos (Keeling) Islands': 'CC', 
'Colombia': 'CO', 
'Comoros': 'KM', 
'Congo': 'CG', 
'Congo, the Democratic Republic of the': 'CD', 
'Cook Islands': 'CK', 
'Costa Rica': 'CR', 
"Cote d'Ivoire": 'CI', 
'Croatia': 'HR', 
'Cuba': 'CU', 
'Curaçao': 'CW', 
'Cyprus': 'CY', 
'Czechia': 'CZ', 
'Denmark': 'DK', 
'Djibouti': 'DJ', 
'Dominica': 'DM', 
'Dominican republic': 'DO', 
'Ecuador': 'EC', 
'Egypt': 'EG', 
'El Salvador': 'SV', 
'Equatorial Guinea': 'GQ', 
'Eritrea': 'ER', 
'Estonia': 'EE', 
'Ethiopia': 'ET', 
'Falkland Islands (Malvinas)': 'FK', 'Faroe Islands': 'FO', 'Fiji': 'FJ', 'Finland': 'FI', 'France': 'FR', 'French Guiana': 'GF', 
'French Polynesia': 'PF', 'French Southern Territories': 'TF', 'Gabon': 'GA', 'Gambia': 'GM', 'Georgia': 'GE', 'Germany': 'DE', 
'Ghana': 'GH', 'Gibraltar': 'GI', 'Greece': 'GR', 'Greenland': 'GL', 'Grenada': 'GD', 'Guadeloupe': 'GP', 'Guam': 'GU', 'Guatemala': 'GT', 
'Guernsey': 'GG', 'Guinea': 'GN', 'Guinea-Bissau': 'GW', 'Guyana': 'GY', 'Haiti': 'HT', 'Heard Island and McDonald Islands': 'HM', 
'Holy See': 'VA', 'Honduras': 'HN', 'Hong Kong': 'HK', 'Hungary': 'HU', 'Iceland': 'IS', 'India': 'IN', 'Indonesia': 'ID', 'Iran': 'IR', 
'Iraq': 'IQ', 'Ireland': 'IE', 'Isle of Man': 'IM', 'Israel': 'IL', 'Italy': 'IT', 'Jamaica': 'JM', 'Japan': 'JP', 'Jersey': 'JE', 
'Jordan': 'JO', 'Kazakhstan': 'KZ', 'Kenya': 'KE', 'Kiribati': 'KI', "Democratic People's Republic of Korea": 'KP', 'S. Korea': 'KR', 
'Kuwait': 'KW', 'Kyrgyzstan': 'KG', "Lao People's Democratic Republic": 'LA', 'Latvia': 'LV', 'Lebanon': 'LB', 'Lesotho': 'LS', 
'Liberia': 'LR', 'Libya': 'LY', 'Liechtenstein': 'LI', 'Lithuania': 'LT', 'Luxembourg': 'LU', 'Macau': 'MO', 'North Macedonia': 'MK', 
'Madagascar': 'MG', 'Malawi': 'MW', 'Malaysia': 'MY', 'Maldives': 'MV', 'Mali': 'ML', 'Malta': 'MT', 'Marshall Islands': 'MH', 
'Martinique': 'MQ', 'Mauritania': 'MR', 'Mauritius': 'MU', 'Mayotte': 'YT', 'Mexico': 'MX', 'Federated States of Micronesia': 'FM', 
'Moldova': 'MD', 'Monaco': 'MC', 'Mongolia': 'MN', 'Montenegro': 'ME', 'Montserrat': 'MS', 'Morocco': 'MA', 'Mozambique': 'MZ', 
'Myanmar': 'MM', 'Namibia': 'NA', 'Nauru': 'NR', 'Nepal': 'NP', 'Netherlands': 'NL', 'New Caledonia': 'NC', 'New Zealand': 'NZ', 
'Nicaragua': 'NI', 'Niger': 'NE', 'Nigeria': 'NG', 'Niue': 'NU', 'Norfolk Island': 'NF', 'Northern Mariana Islands': 'MP', 
'Norway': 'NO', 'Oman': 'OM', 'Pakistan': 'PK', 'Palau': 'PW', 'Palestine': 'PS', 'Panama': 'PA', 'Papua New Guinea': 'PG', 
'Paraguay': 'PY', 'Peru': 'PE', 'Philippines': 'PH', 'Pitcairn': 'PN', 'Poland': 'PL', 'Portugal': 'PT', 'Puerto Rico': 'PR', 
'Qatar': 'QA', 'Reunion': 'RE', 'Romania': 'RO', 'Russia': 'RU', 'Rwanda': 'RW', 'St. Barth': 'BL', 
'Saint Helena, Ascension and Tristan da Cunha': 'SH', 'Saint Kitts and Nevis': 'KN', 'Saint Lucia': 'LC', 'Saint Martin': 'MF', 
'Saint Pierre and Miquelon': 'PM', 'Saint Vincent and the Grenadines': 'VC', 'Samoa': 'WS', 'San Marino': 'SM', 'Sao Tome and Principe': 'ST', 
'Saudi Arabia': 'SA', 'Senegal': 'SN', 'Serbia': 'RS', 'Seychelles': 'SC', 'Sierra Leone': 'SL', 'Singapore': 'SG', 'Sint Maarten': 'SX', 
'Slovakia': 'SK', 'Slovenia': 'SI', 'Solomon Islands': 'SB', 'Somalia': 'SO', 'South Africa': 'ZA', 
'South Georgia and the South Sandwich Islands': 'GS', 'South Sudan': 'SS', 'Spain': 'ES', 'Sri Lanka': 'LK', 'Sudan': 'SD', 'Suriname': 'SR', 
'Svalbard and Jan Mayen': 'SJ', 'Swaziland': 'SZ', 'Sweden': 'SE', 'Switzerland': 'CH', 'Syria': 'SY', 'Taiwan': 'TW', 'Tajikistan': 'TJ', 
'Tanzania': 'TZ', 'Thailand': 'TH', 'Timor-Leste': 'TL', 'Togo': 'TG', 'Tokelau': 'TK', 'Tonga': 'TO', 'Trinidad and Tobago': 'TT', 
'Tunisia': 'TN', 'Turkey': 'TR', 'Turkmenistan': 'TM', 'Turks and Caicos Islands': 'TC', 'Tuvalu': 'TV', 'Uganda': 'UG', 'Ukraine': 'UA', 
'United Arab Emirates': 'AE', 'Uk': 'GB', 'Usa': 'US', 'United States Minor Outlying Islands': 'UM', 'Uruguay': 'UY', 'Uzbekistan': 'UZ', 
'Vanuatu': 'VU', 'Venezuela': 'VE', 'Vietnam': 'VN', 'British Virgin Islands': 'VG', 'Virgin Islands, U.S.': 'VI', 'Wallis and Futuna': 'WF', 
'Western Sahara': 'EH', 'Yemen': 'YE', 'Zambia': 'ZM', 'Zimbabwe': 'ZW',

'England': 'GB-ENG',
'Northern Ireland' : 'GB-NIR',
'Scotland' : 'GB-SCT',
'Wales': 'GB-WLS'
}