flags={
'af': 'afghanistan', 'ax': 'aland islands', 'al': 'albania', 'dz': 'algeria', 'as': 'american samoa', 'ad': 'andorra', 'ao': 'angola', 
'ai': 'anguilla', 'aq': 'antarctica', 'ag': 'antigua and barbuda', 'ar': 'argentina', 'am': 'armenia', 'aw': 'aruba', 'au': 'australia', 
'at': 'austria', 'az': 'azerbaijan', 'bs': 'bahamas', 'bh': 'bahrain', 'bd': 'bangladesh', 'bb': 'barbados', 'by': 'belarus', 'be': 'belgium', 
'bz': 'belize', 'bj': 'benin', 'bm': 'bermuda', 'bt': 'bhutan', 'bo': 'bolivia', 'bq': 'bonaire', 'ba': 'bosnia and herzegovina', 
'bw': 'botswana', 'bv': 'bouvet island', 'br': 'brazil', 'io': 'british indian ocean territory', 'bn': 'brunei', 'bg': 'bulgaria', 
'bf': 'burkina faso', 'bi': 'burundi', 'kh': 'cambodia', 'cm': 'cameroon', 'ca': 'canada', 'cv': 'cape verde', 'ky': 'cayman islands', 
'cf': 'central african republic', 'td': 'chad', 'cl': 'chile', 'cn': 'china', 'cx': 'christmas island', 'cc': 'cocos islands', 
'co': 'colombia', 'km': 'comoros', 'cg': 'congo', 'cd': 'democratic republic of the congo', 'ck': 'cook islands', 'cr': 'costa rica', 
'ci': "cote d'ivoire", 'hr': 'croatia', 'cu': 'cuba', 'cw': 'curaçao', 'cy': 'cyprus', 'cz': 'czechia', 'dk': 'denmark', 'dj': 'djibouti', 
'dm': 'dominica', 'do': 'dominican republic', 'ec': 'ecuador', 'eg': 'egypt', 'sv': 'el salvador', 'gq': 'equatorial guinea', 'er': 'eritrea', 
'ee': 'estonia', 'et': 'ethiopia', 'fk': 'falkland islands', 'fo': 'faroe islands', 'fj': 'fiji', 'fi': 'finland', 'fr': 'france', 
'gf': 'french guiana', 'pf': 'french polynesia', 'tf': 'french southern territories', 'ga': 'gabon', 'gm': 'gambia', 'ge': 'georgia', 
'de': 'germany', 'gh': 'ghana', 'gi': 'gibraltar', 'gr': 'greece', 'gl': 'greenland', 'gd': 'grenada', 'gp': 'guadeloupe', 'gu': 'guam', 
'gt': 'guatemala', 'gg': 'guernsey', 'gn': 'guinea', 'gw': 'guinea-bissau', 'gy': 'guyana', 'ht': 'haiti', 
'hm': 'heard island and mcdonald islands', 'va': 'vatican city', 'hn': 'honduras', 'hk': 'hong kong', 'hu': 'hungary', 'is': 'iceland', 
'in': 'india', 'id': 'indonesia', 'ir': 'iran', 'iq': 'iraq', 'ie': 'ireland', 'im': 'isle of man', 'il': 'israel', 'it': 'italy', 
'jm': 'jamaica', 'jp': 'japan', 'je': 'jersey', 'jo': 'jordan', 'kz': 'kazakhstan', 'ke': 'kenya', 'ki': 'kiribati', 
'kp': "north korea", 'kr': 'south korea', 'kw': 'kuwait', 'kg': 'kyrgyzstan', 'la': "lao people's democratic republic", 
'lv': 'latvia', 'lb': 'lebanon', 'ls': 'lesotho', 'lr': 'liberia', 'ly': 'libya', 'li': 'liechtenstein', 'lt': 'lithuania', 'lu': 'luxembourg', 
'mo': 'macau', 'mk': 'north macedonia', 'mg': 'madagascar', 'mw': 'malawi', 'my': 'malaysia', 'mv': 'maldives', 'ml': 'mali', 
'mt': 'malta', 'mh': 'marshall islands', 'mq': 'martinique', 'mr': 'mauritania', 'mu': 'mauritius', 'yt': 'mayotte', 'mx': 'mexico', 
'fm': 'federated states of micronesia', 'md': 'moldova', 'mc': 'monaco', 'mn': 'mongolia', 'me': 'montenegro', 'ms': 'montserrat', 
'ma': 'morocco', 'mz': 'mozambique', 'mm': 'myanmar', 'na': 'namibia', 'nr': 'nauru', 'np': 'nepal', 'nl': 'netherlands', 
'nc': 'new caledonia', 'nz': 'new zealand', 'ni': 'nicaragua', 'ne': 'niger', 'ng': 'nigeria', 'nu': 'niue', 'nf': 'norfolk island', 
'mp': 'northern mariana islands', 'no': 'norway', 'om': 'oman', 'pk': 'pakistan', 'pw': 'palau', 'ps': 'palestine', 'pa': 'panama', 
'pg': 'papua new guinea', 'py': 'paraguay', 'pe': 'peru', 'ph': 'philippines', 'pn': 'pitcairn islands', 'pl': 'poland', 'pt': 'portugal', 
'pr': 'puerto rico', 'qa': 'qatar', 're': 'reunion', 'ro': 'romania', 'ru': 'russia', 'rw': 'rwanda', 'bl': 'saint barthelemy', 
'sh': 'saint helena, ascension and tristan da cunha', 'kn': 'saint kitts and nevis', 'lc': 'saint lucia', 'mf': 'saint martin', 
'pm': 'saint pierre and miquelon', 'vc': 'saint vincent and the grenadines', 'ws': 'samoa', 'sm': 'san marino', 'st': 'sao tome and principe', 
'sa': 'saudi arabia', 'sn': 'senegal', 'rs': 'serbia', 'sc': 'seychelles', 'sl': 'sierra leone', 'sg': 'singapore', 
'sx': 'sint maarten', 'sk': 'slovakia', 'si': 'slovenia', 'sb': 'solomon islands', 'so': 'somalia', 'za': 'south africa', 
'gs': 'south georgia and the south sandwich islands', 'ss': 'south sudan', 'es': 'spain', 'lk': 'sri lanka', 'sd': 'sudan', 
'sr': 'suriname', 'sj': 'svalbard and jan mayen', 'sz': 'swaziland', 'se': 'sweden', 'ch': 'switzerland', 'sy': 'syria', 
'tw': 'taiwan', 'tj': 'tajikistan', 'tz': 'tanzania', 'th': 'thailand', 'tl': 'timor-leste', 'tg': 'togo', 'tk': 'tokelau', 
'to': 'tonga', 'tt': 'trinidad and tobago', 'tn': 'tunisia', 'tr': 'turkey', 'tm': 'turkmenistan', 'tc': 'turks and caicos islands', 
'tv': 'tuvalu', 'ug': 'uganda', 'ua': 'ukraine', 'ae': 'united arab emirates', 'gb': 'uk', 'us': 'usa', 
'um': 'united states minor outlying islands', 'uy': 'uruguay', 'uz': 'uzbekistan', 'vu': 'vanuatu', 've': 'venezuela', 'vn': 'vietnam', 
'vg': 'british virgin islands', 'vi': 'u.s. virgin islands', 'wf': 'wallis and futuna', 'eh': 'western sahara', 'ye': 'yemen', 
'zm': 'zambia', 'zw': 'zimbabwe'
}




"""
for k,v in flags.items():
    flags.update({v: ""})

print(flags)

new_dict = dict([(value, key) for key, value in flags.items()]) 
for k,v in new_dict.items():
    new_dict.update({k: ""})

print(new_dict)


from countryinfo import CountryInfo


new={'afghanistan': '', 'aland islands': '', 'albania': '', 'algeria': '', 'american samoa': '', 'andorra': '', 'angola': '', 'anguilla': '', 'antarctica': '', 'antigua and barbuda': '', 'argentina': '', 'armenia': '', 'aruba': '', 'australia': '', 'austria': '', 'azerbaijan': '', 'bahamas': '', 'bahrain': '', 'bangladesh': '', 'barbados': '', 'belarus': '', 'belgium': '', 'belize': '', 'benin': '', 'bermuda': '', 'bhutan': '', 'bolivia': '', 'bonaire': '', 'bosnia and herzegovina': '', 'botswana': '', 'bouvet island': '', 'brazil': '', 'british indian ocean territory': '', 'brunei': '', 'bulgaria': '', 'burkina faso': '', 'burundi': '', 'cambodia': '', 'cameroon': '', 'canada': '', 'cape verde': '', 'cayman islands': '', 'central african republic': '', 'chad': '', 'chile': '', 'china': '', 'christmas island': '', 'cocos islands': '', 'colombia': '', 'comoros': '', 'congo': '', 'democratic republic of the congo': '', 'cook islands': '', 'costa rica': '', "cote d'ivoire": '', 'croatia': '', 'cuba': '', 'curaçao': '', 'cyprus': '', 'czechia': '', 'denmark': '', 'djibouti': '', 'dominica': '', 'dominican republic': '', 'ecuador': '', 'egypt': '', 'el salvador': '', 'equatorial guinea': '', 'eritrea': '', 'estonia': '', 'ethiopia': '', 'falkland islands': '', 'faroe islands': '', 'fiji': '', 'finland': '', 'france': '', 'french guiana': '', 'french polynesia': '', 'french southern territories': '', 'gabon': '', 'gambia': '', 'georgia': '', 'germany': '', 'ghana': '', 'gibraltar': '', 'greece': '', 'greenland': '', 'grenada': '', 'guadeloupe': '', 'guam': '', 'guatemala': '', 'guernsey': '', 'guinea': '', 'guinea-bissau': '', 'guyana': '', 'haiti': '', 'heard island and mcdonald islands': '', 'vatican city': '', 'honduras': '', 'hong kong': '', 'hungary': '', 'iceland': '', 'india': '', 'indonesia': '', 'iran': '', 'iraq': '', 'ireland': '', 'isle of man': '', 'israel': '', 'italy': '', 'jamaica': '', 'japan': '', 'jersey': '', 'jordan': '', 'kazakhstan': '', 'kenya': '', 'kiribati': '', 'north korea': '', 'south korea': '', 'kuwait': '', 'kyrgyzstan': '', "lao people's democratic republic": '', 'latvia': '', 'lebanon': '', 'lesotho': '', 'liberia': '', 'libya': '', 'liechtenstein': '', 'lithuania': '', 'luxembourg': '', 'macau': '', 'north macedonia': '', 'madagascar': '', 'malawi': '', 'malaysia': '', 'maldives': '', 'mali': '', 'malta': '', 'marshall islands': '', 'martinique': '', 'mauritania': '', 'mauritius': '', 'mayotte': '', 'mexico': '', 'federated states of micronesia': '', 'moldova': '', 'monaco': '', 'mongolia': '', 'montenegro': '', 'montserrat': '', 'morocco': '', 'mozambique': '', 'myanmar': '', 'namibia': '', 'nauru': '', 'nepal': '', 'netherlands': '', 'new caledonia': '', 'new zealand': '', 'nicaragua': '', 'niger': '', 'nigeria': '', 'niue': '', 'norfolk island': '', 'northern mariana islands': '', 'norway': '', 'oman': '', 'pakistan': '', 'palau': '', 'palestine': '', 'panama': '', 'papua new guinea': '', 'paraguay': '', 'peru': '', 'philippines': '', 'pitcairn islands': '', 'poland': '', 'portugal': '', 'puerto rico': '', 'qatar': '', 'reunion': '', 'romania': '', 'russia': '', 'rwanda': '', 'saint barthelemy': '', 'saint helena, ascension and tristan da cunha': '', 'saint kitts and nevis': '', 'saint lucia': '', 'saint martin': '', 'saint pierre and miquelon': '', 'saint vincent and the grenadines': '', 'samoa': '', 'san marino': '', 'sao tome and principe': '', 'saudi arabia': '', 'senegal': '', 'serbia': '', 'seychelles': '', 'sierra leone': '', 'singapore': '', 'sint maarten': '', 'slovakia': '', 'slovenia': '', 'solomon islands': '', 'somalia': '', 'south africa': '', 'south georgia and the south sandwich islands': '', 'south sudan': '', 'spain': '', 'sri lanka': '', 'sudan': '', 'suriname': '', 'svalbard and jan mayen': '', 'swaziland': '', 'sweden': '', 'switzerland': '', 'syria': '', 'taiwan': '', 'tajikistan': '', 'tanzania': '', 'thailand': '', 'timor-leste': '', 'togo': '', 'tokelau': '', 'tonga': '', 'trinidad and tobago': '', 'tunisia': '', 'turkey': '', 'turkmenistan': '', 'turks and caicos islands': '', 'tuvalu': '', 'uganda': '', 'ukraine': '', 'united arab emirates': '', 'uk': '', 'usa': '', 'united states minor outlying islands': '', 'uruguay': '', 'uzbekistan': '', 'vanuatu': '', 'venezuela': '', 'vietnam': '', 'british virgin islands': '', 'u.s. virgin islands': '', 'wallis and futuna': '', 'western sahara': '', 'yemen': '', 'zambia': '', 'zimbabwe': ''}



for k,v in capitals.items():
    capitals.update({k.lower(): v.lower()})

print(cap)





for i in flags:
    country = CountryInfo(i)
    print(country.capital())


for key, value in new.items():
    try:
        country = CountryInfo(key)
        new[key] = country.latlng()
    except:
        new[key] = ""
print(new)
"""



capitals = {
  'afghanistan': 'Kabul',
  'aland islands': 'Mariehamn',
  'albania': 'Tirana',
  'algeria': 'Algiers',
  'american samoa': 'Pago Pago',
  'andorra': 'Andorra la Vella',
  'angola': 'Luanda',
  'anguilla': 'The Valley',
  'antarctica': 'This country doesn\'t have a capital (that may help you a lot)',
  'antigua and barbuda': "Saint John's",
  'argentina': 'Buenos Aires',
  'armenia': 'Yerevan',
  'aruba': 'Oranjestad',
  'australia': 'Canberra',
  'austria': 'Vienna',
  'azerbaijan': 'Baku',
  'bahamas': 'Nassau',
  'bahrain': 'Manama',
  'bangladesh': 'Dhaka',
  'barbados': 'Bridgetown',
  'belarus': 'Minsk',
  'belgium': 'Brussels',
  'belize': 'Belmopan',
  'benin': 'Porto-Novo',
  'bermuda': 'Hamilton',
  'bhutan': 'Thimphu',
  'bolivia': 'Sucre',
  'bonaire': 'Kralendijk',
  'bosnia and herzegovina': 'Sarajevo',
  'botswana': 'Gaborone',
  'bouvet island': 'No Capital, too small for that',
  'brazil': 'Brasília',
  'british indian ocean territory': 'Diego Garcia',
  'brunei': 'Bandar Seri Begawan',
  'bulgaria': 'Sofia',
  'burkina faso': 'Ouagadougou',
  'burundi': 'Bujumbura',
  'cambodia': 'Phnom Penh',
  'cameroon': 'Yaoundé',
  'canada': 'Ottawa',
  'cape verde': 'Praia',
  'cayman islands': 'George Town',
  'central african republic': 'Bangui',
  'chad': "N'Djamena",
  'chile': 'Santiago',
  'china': 'Beijing',
  'christmas island': 'Flying Fish Cove',
  'cocos islands': 'West Island',
  'colombia': 'Bogotá',
  'comoros': 'Moroni',
  'congo': 'Brazzaville',
  'democratic republic of the congo': 'Kinshasa',
  'cook islands': 'Avarua',
  'costa rica': 'San José',
  "cote d'ivoire": 'Yamoussoukro',
  'croatia': 'Zagreb',
  'cuba': 'Havana',
  'curaçao': 'Willemstad',
  'cyprus': 'Nicosia',
  'czechia': 'Prague',
  'denmark': 'Copenhagen',
  'djibouti': 'Djibouti',
  'dominica': 'Roseau',
  'dominican republic': 'Santo Domingo',
  'ecuador': 'Quito',
  'egypt': 'Cairo',
  'el salvador': 'San Salvador',
  'equatorial guinea': 'Malabo',
  'eritrea': 'Asmara',
  'estonia': 'Tallinn',
  'ethiopia': 'Addis Ababa',
  'falkland islands': 'Stanley',
  'faroe islands': 'Tórshavn',
  'fiji': 'Suva',
  'finland': 'Helsinki',
  'france': 'Paris',
  'french guiana': 'Cayenne',
  'french polynesia': 'Papeetē',
  'french southern territories': 'No Capital (that may help you)',
  'gabon': 'Libreville',
  'gambia': 'Banjul',
  'georgia': 'Tbilisi',
  'germany': 'Berlin',
  'ghana': 'Accra',
  'gibraltar': 'Gibraltar',
  'greece': 'Athens',
  'greenland': 'Nuuk',
  'grenada': "St. George's",
  'guadeloupe': 'Basse-Terre',
  'guam': 'Hagåtña',
  'guatemala': 'Guatemala City',
  'guernsey': 'St. Peter Port',
  'guinea': 'Conakry',
  'guinea-bissau': 'Bissau',
  'guyana': 'Georgetown',
  'haiti': 'Port-au-Prince',
  'heard island and mcdonald islands': 'No Capital (that may help you)',
  'vatican city': 'Vatican City',
  'honduras': 'Tegucigalpa',
  'hong kong': 'City of Victoria',
  'hungary': 'Budapest',
  'iceland': 'Reykjavik',
  'india': 'New Delhi',
  'indonesia': 'Jakarta',
  'iran': 'Tehran',
  'iraq': 'Baghdad',
  'ireland': 'Dublin',
  'isle of man': 'Douglas',
  'israel': 'Jerusalem',
  'italy': 'Rome',
  'jamaica': 'Kingston',
  'japan': 'Tokyo',
  'jersey': 'Saint Helier',
  'jordan': 'Amman',
  'kazakhstan': 'Astana',
  'kenya': 'Nairobi',
  'kiribati': 'South Tarawa',
  "north korea": 'Pyongyang',
  'south korea': 'Seoul',
  'kuwait': 'Kuwait City',
  'kyrgyzstan': 'Bishkek',
  "lao people's democratic republic": 'Vientiane',
  'latvia': 'Riga',
  'lebanon': 'Beirut',
  'lesotho': 'Maseru',
  'liberia': 'Monrovia',
  'libya': 'Tripoli',
  'liechtenstein': 'Vaduz',
  'lithuania': 'Vilnius',
  'luxembourg': 'Luxembourg',
  'macau': 'No Capital, it\'s an administrative region',
  'north macedonia': 'Skopje',
  'madagascar': 'Antananarivo',
  'malawi': 'Lilongwe',
  'malaysia': 'Kuala Lumpur',
  'maldives': 'Malé',
  'mali': 'Bamako',
  'malta': 'Valletta',
  'marshall islands': 'Majuro',
  'martinique': 'Fort-de-France',
  'mauritania': 'Nouakchott',
  'mauritius': 'Port Louis',
  'mayotte': 'Mamoudzou',
  'mexico': 'Mexico City',
  'federated states of micronesia': 'Palikir',
  'moldova': 'Chișinău',
  'monaco': 'Monaco',
  'mongolia': 'Ulan Bator',
  'montenegro': 'Podgorica',
  'montserrat': 'Plymouth',
  'morocco': 'Rabat',
  'mozambique': 'Maputo',
  'myanmar': 'Naypyitaw',
  'namibia': 'Windhoek',
  'nauru': 'Yaren',
  'nepal': 'Kathmandu',
  'netherlands': 'Amsterdam',
  'new caledonia': 'Nouméa',
  'new zealand': 'Wellington',
  'nicaragua': 'Managua',
  'niger': 'Niamey',
  'nigeria': 'Abuja',
  'niue': 'Alofi',
  'norfolk island': 'Kingston',
  'northern mariana islands': 'Saipan',
  'norway': 'Oslo',
  'oman': 'Muscat',
  'pakistan': 'Islamabad',
  'palau': 'Ngerulmud',
  'palestine': 'Jerusalem',
  'panama': 'Panama City',
  'papua new guinea': 'Port Moresby',
  'paraguay': 'Asunción',
  'peru': 'Lima',
  'philippines': 'Manila',
  'pitcairn islands': 'Adamstown',
  'poland': 'Warsaw',
  'portugal': 'Lisbon',
  'puerto rico': 'San Juan',
  'qatar': 'Doha',
  'reunion': 'Saint-Denis',
  'romania': 'Bucharest',
  'russia': 'Moscow',
  'rwanda': 'Kigali',
  'saint barthelemy': 'Gustavia',
  'saint helena, ascension and tristan da cunha': 'Jamestown (Also, the name is veryyy longgg)',
  'saint kitts and nevis': 'Basseterre',
  'saint lucia': 'Castries',
  'saint martin': 'Marigot',
  'saint pierre and miquelon': 'Saint-Pierre',
  'saint vincent and the grenadines': 'Kingstown',
  'samoa': 'Apia',
  'san marino': 'City of San Marino',
  'sao tome and principe': 'Sao Tome',
  'saudi arabia': 'Riyadh',
  'senegal': 'Dakar',
  'serbia': 'Belgrade',
  'seychelles': 'Victoria',
  'sierra leone': 'Freetown',
  'singapore': 'Singapore',
  'sint maarten': 'Philipsburg',
  'slovakia': 'Bratislava',
  'slovenia': 'Ljubljana',
  'solomon islands': 'Honiara',
  'somalia': 'Mogadishu',
  'south africa': 'Pretoria',
  'south georgia and the south sandwich islands': 'King Edward Point',
  'south sudan': 'Juba',
  'spain': 'Madrid',
  'sri lanka': 'Colombo',
  'sudan': 'Khartoum',
  'suriname': 'Paramaribo',
  'svalbard and jan mayen': 'Longyearbyen',
  'swaziland': 'Lobamba',
  'sweden': 'Stockholm',
  'switzerland': 'Bern',
  'syria': 'Damascus',
  'taiwan': 'Taipei',
  'tajikistan': 'Dushanbe',
  'tanzania': 'Dodoma',
  'thailand': 'Bangkok',
  'timor-leste': 'Dili',
  'togo': 'Lomé',
  'tokelau': 'Fakaofo',
  'tonga': "Nuku'alofa",
  'trinidad and tobago': 'Port of Spain',
  'tunisia': 'Tunis',
  'turkey': 'Ankara',
  'turkmenistan': 'Ashgabat',
  'turks and caicos islands': 'Cockburn Town',
  'tuvalu': 'Funafuti',
  'uganda': 'Kampala',
  'ukraine': 'Kiev',
  'united arab emirates': 'Abu Dhabi',
  'uk': 'London',
  'usa': 'Washington D.C.',
  'united states minor outlying islands': 'Too small to have a capital',
  'uruguay': 'Montevideo',
  'uzbekistan': 'Tashkent',
  'vanuatu': 'Port Vila',
  'venezuela': 'Caracas',
  'vietnam': 'Hanoi',
  'british virgin islands': 'Road Town',
  'u.s. virgin islands': 'Charlotte Amalie',
  'wallis and futuna': 'Mata-Utu',
  'western sahara': 'El Aaiún',
  'yemen': "Sana'a",
  'zambia': 'Lusaka',
  'zimbabwe': 'Harare'
}





lat_long = {
  'afghanistan': [33, 65],
  'aland islands': '',
  'albania': [41, 20],
  'algeria': [28, 3],
  'american samoa': [-14.33333333, -170],
  'andorra': '',
  'angola': [-12.5, 18.5],
  'anguilla': [18.25, -63.16666666],
  'antarctica': '',
  'antigua and barbuda': [17.05, -61.8],
  'argentina': [-34, -64],
  'armenia': [40, 45],
  'aruba': [12.5, -69.96666666],
  'australia': [-27, 133],
  'austria': [47.33333333, 13.33333333],
  'azerbaijan': [40.5, 47.5],
  'bahamas': '',
  'bahrain': [26, 50.55],
  'bangladesh': [24, 90],
  'barbados': [13.16666666, -59.53333333],
  'belarus': [53, 28],
  'belgium': [50.83333333, 4],
  'belize': [17.25, -88.75],
  'benin': [9.5, 2.25],
  'bermuda': [32.33333333, -64.75],
  'bhutan': [27.5, 90.5],
  'bolivia': [-17, -65],
  'bonaire': '',
  'bosnia and herzegovina': [44, 18],
  'botswana': [-22, 24],
  'bouvet island': '',
  'brazil': [-10, -55],
  'british indian ocean territory': [-6, 71.5],
  'brunei': [4.5, 114.66666666],
  'bulgaria': [43, 25],
  'burkina faso': [13, -2],
  'burundi': [-3.5, 30],
  'cambodia': [13, 105],
  'cameroon': [6, 12],
  'canada': [60, -95],
  'cape verde': [16, -24],
  'cayman islands': [19.5, -80.5],
  'central african republic': [7, 21],
  'chad': [15, 19],
  'chile': [-30, -71],
  'china': [35, 105],
  'christmas island': [-10.5, 105.66666666],
  'cocos islands': '',
  'colombia': [4, -72],
  'comoros': [-12.16666666, 44.25],
  'congo': '',
  'democratic republic of the congo': [0, 25],
  'cook islands': [-21.23333333, -159.76666666],
  'costa rica': [10, -84],
  "cote d'ivoire": '',
  'croatia': [45.16666666, 15.5],
  'cuba': [21.5, -80],
  'curaçao': '',
  'cyprus': [35, 33],
  'czechia': '',
  'denmark': [56, 10],
  'djibouti': [11.5, 43],
  'dominica': [15.41666666, -61.33333333],
  'dominican republic': [19, -70.66666666],
  'ecuador': [-2, -77.5],
  'egypt': [27, 30],
  'el salvador': [13.83333333, -88.91666666],
  'equatorial guinea': [2, 10],
  'eritrea': [15, 39],
  'estonia': [59, 26],
  'ethiopia': [8, 38],
  'falkland islands': [-51.75, -59],
  'faroe islands': [62, -7],
  'fiji': [-18, 175],
  'finland': [64, 26],
  'france': [46, 2],
  'french guiana': [4, -53],
  'french polynesia': [-15, -140],
  'french southern territories': '',
  'gabon': [-1, 11.75],
  'gambia': '',
  'georgia': [42, 43.5],
  'germany': [51, 9],
  'ghana': [8, -2],
  'gibraltar': [36.13333333, -5.35],
  'greece': [39, 22],
  'greenland': [72, -40],
  'grenada': [12.11666666, -61.66666666],
  'guadeloupe': [16.25, -61.583333],
  'guam': [13.46666666, 144.78333333],
  'guatemala': [15.5, -90.25],
  'guernsey': [49.46666666, -2.58333333],
  'guinea': [11, -10],
  'guinea-bissau': [12, -15],
  'guyana': [5, -59],
  'haiti': [19, -72.41666666],
  'heard island and mcdonald islands': [-53.1, 72.51666666],
  'vatican city': '',
  'honduras': [15, -86.5],
  'hong kong': [22.25, 114.16666666],
  'hungary': [47, 20],
  'iceland': [65, -18],
  'india': [20, 77],
  'indonesia': [-5, 120],
  'iran': [32, 53],
  'iraq': [33, 44],
  'ireland': [53, -8],
  'isle of man': [54.25, -4.5],
  'israel': [31.5, 34.75],
  'italy': [42.83333333, 12.83333333],
  'jamaica': [18.25, -77.5],
  'japan': [36, 138],
  'jersey': [49.25, -2.16666666],
  'jordan': [31, 36],
  'kazakhstan': [48, 68],
  'kenya': [1, 38],
  'kiribati': [1.41666666, 173],
  'north korea': [40, 127],
  'south korea': [37, 127.5],
  'kuwait': [29.5, 45.75],
  'kyrgyzstan': [41, 75],
  "lao people's democratic republic": [18, 105],
  'latvia': [57, 25],
  'lebanon': [33.83333333, 35.83333333],
  'lesotho': [-29.5, 28.5],
  'liberia': [6.5, -9.5],
  'libya': [25, 17],
  'liechtenstein': [47.26666666, 9.53333333],
  'lithuania': [56, 24],
  'luxembourg': [49.75, 6.16666666],
  'macau': [22.16666666, 113.55],
  'north macedonia': '',
  'madagascar': [-20, 47],
  'malawi': [-13.5, 34],
  'malaysia': [2.5, 112.5],
  'maldives': [3.25, 73],
  'mali': [17, -4],
  'malta': [35.83333333, 14.58333333],
  'marshall islands': [9, 168],
  'martinique': [14.666667, -61],
  'mauritania': [20, -12],
  'mauritius': [-20.28333333, 57.55],
  'mayotte': [-12.83333333, 45.16666666],
  'mexico': [23, -102],
  'federated states of micronesia': [6.91666666, 158.25],
  'moldova': [47, 29],
  'monaco': [43.73333333, 7.4],
  'mongolia': [46, 105],
  'montenegro': '',
  'montserrat': [16.75, -62.2],
  'morocco': [32, -5],
  'mozambique': [-18.25, 35],
  'myanmar': '',
  'namibia': [-22, 17],
  'nauru': [-0.53333333, 166.91666666],
  'nepal': [28, 84],
  'netherlands': [52.5, 5.75],
  'new caledonia': [-21.5, 165.5],
  'new zealand': [-41, 174],
  'nicaragua': [13, -85],
  'niger': [16, 8],
  'nigeria': [10, 8],
  'niue': [-19.03333333, -169.86666666],
  'norfolk island': [-29.03333333, 167.95],
  'northern mariana islands': [15.2, 145.75],
  'norway': [62, 10],
  'oman': [21, 57],
  'pakistan': [30, 70],
  'palau': [7.5, 134.5],
  'palestine': '',
  'panama': [9, -80],
  'papua new guinea': [-6, 147],
  'paraguay': [-23, -58],
  'peru': [-10, -76],
  'philippines': [13, 122],
  'pitcairn islands': [-25.06666666, -130.1],
  'poland': [52, 20],
  'portugal': [39.5, -8],
  'puerto rico': [18.25, -66.5],
  'qatar': [25.5, 51.25],
  'reunion': [-21.15, 55.5],
  'romania': [46, 25],
  'russia': [60, 100],
  'rwanda': [-2, 30],
  'saint barthelemy': '',
  'saint helena, ascension and tristan da cunha': '',
  'saint kitts and nevis': [17.33333333, -62.75],
  'saint lucia': [13.88333333, -60.96666666],
  'saint martin': '',
  'saint pierre and miquelon': [46.83333333, -56.33333333],
  'saint vincent and the grenadines': [13.25, -61.2],
  'samoa': [-13.58333333, -172.33333333],
  'san marino': [43.76666666, 12.41666666],
  'sao tome and principe': '',
  'saudi arabia': [25, 45],
  'senegal': [14, -14],
  'serbia': [44.1305021, 16.4284181],
  'seychelles': [-4.58333333, 55.66666666],
  'sierra leone': [8.5, -11.5],
  'singapore': [1.36666666, 103.8],
  'sint maarten': '',
  'slovakia': [48.66666666, 19.5],
  'slovenia': [46.11666666, 14.81666666],
  'solomon islands': [-8, 159],
  'somalia': [10, 49],
  'south africa': [-29, 24],
  'south georgia and the south sandwich islands': [-54.5, -37],
  'south sudan': [7, 30],
  'spain': [40, -4],
  'sri lanka': [7, 81],
  'sudan': [15, 30],
  'suriname': [4, -56],
  'svalbard and jan mayen': [78, 20],
  'swaziland': [-26.5, 31.5],
  'sweden': [62, 15],
  'switzerland': [47, 8],
  'syria': [35, 38],
  'taiwan': [23.5, 121],
  'tajikistan': [39, 71],
  'tanzania': [-6, 35],
  'thailand': [15, 100],
  'timor-leste': '',
  'togo': [8, 1.16666666],
  'tokelau': [-9, -172],
  'tonga': [-20, -175],
  'trinidad and tobago': [11, -61],
  'tunisia': [34, 9],
  'turkey': [39, 35],
  'turkmenistan': [40, 60],
  'turks and caicos islands': '',
  'tuvalu': [-8, 178],
  'uganda': [1, 32],
  'ukraine': [49, 32],
  'united arab emirates': [24, 54],
  'uk': [54, -2],
  'usa': [38, -97],
  'united states minor outlying islands': '',
  'uruguay': [-33, -56],
  'uzbekistan': [41, 64],
  'vanuatu': [-16, 167],
  'venezuela': [8, -66],
  'vietnam': [16.16666666, 107.83333333],
  'british virgin islands': '',
  'u.s. virgin islands': '',
  'wallis and futuna': [-13.3, -176.2],
  'western sahara': [24.5, -13],
  'yemen': [15, 48],
  'zambia': [-15, 30],
  'zimbabwe': [-20, 30]
}


import pandas as pd
from mpl_toolkits.basemap import Basemap
import numpy as np
import matplotlib.pyplot as plt
 
def plot_map(lat,lon):
    # Make a data frame with the GPS of a few cities:
    data = pd.DataFrame({
    'lat':[lat],
    'lon':[lon],
    'name':['Advice']
    })
    
    # A basic map
    m=Basemap(llcrnrlon=-160, llcrnrlat=-75,urcrnrlon=160,urcrnrlat=80)
    m.drawmapboundary(fill_color='#A6CAE0', linewidth=0)
    m.fillcontinents(color='grey', alpha=0.7, lake_color='grey')
    m.drawcoastlines(linewidth=0.1, color="white")
    
    # Add a marker per city of the data frame!
    m.plot(data['lat'], data['lon'], linestyle='none', marker="o", markersize=16, alpha=0.6, c="orange", markeredgecolor="black", markeredgewidth=1)
    plt.show()
    plt.savefig('advice.png')